config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root "rooms#index"

  resources :users do
    resources :rooms, only: :create
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :static_pages
  namespace :api do
    resources :comments
  end
  resources :rooms do
    resources :photos
    resources :comments
  end
  resources :photos
  resources :favorites
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipient = User.where(id: conversation_params[:recipient])
    conversation = current_user.send_message(recipient, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Tin nhắn của bạn được gửi thành công"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Tin nhắn trả lời của bạn đã gửi thành công"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private
  def conversation_params
    params.require(:conversation).permit(:subject, :body, :recipient)
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "Chi tiết", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>

    <%= f.hidden_field :recipient, value: params[:recipient] %>

    <div class="form-group">
      <%= f.label :subject, "Chủ đề" %>
      <%= f.text_field :subject, placeholder: "Chủ đề", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message, "Tin nhắn" %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Nội dung", rows: 4  %>
    </div>
    <%= f.submit "Gửi tin", class: "btn btn-success" %>
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.name %> <br>
          <small><b>Chủ đề: </b><%= message.subject %></small><br>
          <small><b>Ngày gửi: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Khôi phục', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Xóa', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Chắc xóa chứ bạn?'} %>
    <% end %>
  </div>
</div>

<div>
  <div class="spacer" ></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <% if !conversation.is_trashed?(current_user) %>
        <div class="panel-footer">
          <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
              <div class="form-group">
                <%= f.text_area :body, placeholder: "Trả lời tin nhắn", rows: 4, class: "form-control" %>
              </div>
              <%= f.submit "Trả lời", class: 'btn btn-danger pull-right' %>
          <% end %>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>

</div>