config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root "rooms#index"

  resources :users do
    resources :rooms, only: :create
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :static_pages
  namespace :api do
    resources :comments
  end
  resources :rooms do
    resources :photos
    resources :comments
  end
  resources :photos
  resources :favorites
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/views/mailbox/_folder_view.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <div class="spacer"></div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
         <% if is_conversation %>
          <%= render 'conversations/form' %>
        <% else %>
          <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Hộp thư đến</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Thư đã gửi</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Thùng rác</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>