config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root "rooms#index"

  resources :users do
    resources :rooms, only: :create
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :static_pages
  namespace :api do
    resources :comments
  end
  resources :rooms do
    resources :photos
    resources :comments
  end
  resources :photos
  resources :favorites
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos,
    reject_if: proc { |attributes| attributes[:image].blank? }, allow_destroy: true

  enum home_type: [:"nhà riêng", :"khách sạn", :"Khu chung cư"]
  enum room_type: [:"phòng riêng", :"phòng chung"]
  PROVINCES = [:"An Giang", :"Bà Rịa - Vũng Tàu", :"Bạc Liêu", :"Bắc Cạn",
    :"Bắc Giang", :"Bắc Ninh", :"Bến tre", :"Bình Dương", :"Bình Định",
    :"Bình Phước", :"Bình Thuận", :"Cà Mau", :"Cần Thơ",:"Đà Nẵng",
    :"Đắk Lắk",:"Đắk Nông", :"Đồng Nai", :"Đồng Tháp",
    :"Điện Biên", :"Gia Lai", :"Hà Giang", :"Hà Nam",
    :"Hà Nội", :"Hà Tĩnh", :"Hải Dương", :"Hải Phòng", :"Hòa Bình", :"Hậu Giang",
    :"Hưng Yên", :"TP. Hồ Chí Minh", :"Khánh Hòa", :"Kiên Giang", :"Kon Tum",
    :"Lai Châu", :"Lào Cai", :"Lạng Sơn", :"Lâm Đồng", :"Long An", :"Nam Định",
    :"Nghệ An", :"Ninh Bình", :"Ninh Thuận", :"Phú Thọ", :"Phú Yên", :"Quảng Bình",
    :"Quảng Nam", :"Quảng Ngãi", :"Quảng Ninh", :"Quảng Trị", :"Sóc Trăng", :"Sơn La",
    :"Tây Ninh", :"Thái Bình", :"Thái Nguyên", :"Thanh Hóa", :"Thừa Thiên - Huế",
    :"Tiền Giang", :"Trà Vinh", :"Tuyên Quang", :"Vĩnh Long", :"Vĩnh Phúc", :"Yên Bái"]

  def self.search(search)
    where("province LIKE ?","%#{search}%")
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  load_and_authorize_resource

  def index
    if params[:search]
      @rooms = Room.search(params[:search]).order("created_at DESC")
    else
      @rooms = Room.all.order('created_at DESC')
    end
  end

  def show
    @comments = Comment.where("room_id = ?", @room.id)
    respond_to do |format|
      format.html
      format.json {render json: @room.as_json(only: [:lat, :lng])}
    end
  end

  def new
    6.times{@room.photos.build}
  end

  def edit

  end

  def update

  end

  def create
    @room = current_user.rooms.new room_params
    if @room.save!
      flash[:info] = "Tạo phòng thành công!"
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def room_params
    params.require(:room).permit(:name, :lat, :lng, :address, :price, :number_person,
      :user_id, :home_type, :room_type, :province, :rule, :description, :internet, :tv, :wifi, :kid, :aircondition,
      :elevator, :kitchen, :heating, :computer, photos_attributes: [:id, :image, :_destroy])
  end
end

app/views/rooms/_comment_form.html.erb
<div id="comment">
  <div class="col-md-12">
    <% @comments.each do |comment| %>
      <div class="col-md-2" >
        <%= comment.user.name %>
      </div>
      <div class="col-md-10" >
        <p><%= comment.content %></p>
      </div>
    <% end %>
    <%= form_for [@room,Comment.new], remote: true do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.text_area :content, class: "form-control" %>
      <%= f.submit "Bình luận", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/rooms/_form_maps.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="row" >
  <div class="col-md-12" >
    <div class="col-md-6" >
      <label class="col-md-offset-4">Địa chỉ nhà bạn</label>
      <p id="address"></p>
      <p id="location"></p>
      <%= f.hidden_field :address, id: "room_address" %>
      <%= f.hidden_field :lat, id: "lat" %>
      <%= f.hidden_field :lng, id: "lng" %>
      <div id="googleMap" style="width:550px;height:380px;" ></div>
    </div>
    <div class="col-md-6" >
      <%= f.fields_for :photos do |photo| %>
        <%= photo.label :image, "Thêm ảnh" %>
        <%= photo.file_field :image %>
        <%= photo.check_box :_destroy %>
        <%= photo.label "Xóa" %><br/>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_form_room.html.erb
<div id="room-new">
  <h1>Thêm thông tin phòng</h1>
  <div class="row" >
    <%= form_for [current_user, @room] do |f| %>
      <div id = "room-infor" >
        <div class="col-md-6" >
          <div class="form-group" >
            <%= f.label :Tên_của_phòng %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group" >
            <%= f.label :Miêu_Tả %>
            <%= f.text_area :description, rows: 4 , class: "form-control"%>
          </div>
          <div class="form-group" >
            <%= f.label :home_type, "Loại nhà" %>
            <%= f.select :home_type, Room.home_types.keys,{},{ id: "home-type"} %>
          </div>
          <div class="form-group" >
            <%= f.label :price, "Gía phòng 1 đêm: " %>
            <%= f.number_field :price, step: "any" %><span> &nbsp;VND</span>
          </div>
          <div class="form-group" >
            <%= f.label :number_person, "Số người có thể ở:" %>
            <%= f.number_field :number_person, step: 1 %>
          </div>
          <div class="form-group inline" >
            <%= f.label :room_type, "Loại phòng" %>
            <%= f.select :room_type, Room.room_types.keys,{},{id: "room-type"}%>
          </div>
          <div class="form-group" >
            <%= f.label :province, "Tỉnh thành" %>
            <%= f.select :province, options_for_select(Room::PROVINCES),{},{id: "province"} %>
          </div>
          <div class="form-group" >
            <%= f.label :rule, "Quy định của phòng" %>
            <%= f.text_area :rule, rows: 3, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6" >
          <h2>Trang thiết bị của phòng</h2>
          <div class="form-group" >
            <%= f.check_box :internet %>
            <%= f.label :internet %>
          </div>
          <div class="form-group" >
            <%= f.check_box :tv %>
            <%= f.label :tv, "Ti vi" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :wifi %>
            <%= f.label :wifi, "Wi fi" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :kid %>
            <%= f.label :kid, "Trẻ em" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :aircondition %>
            <%= f.label :aircondition, "Điều hòa" %>
          </div>
          <div class="form-group"  >
            <%= f.check_box :elevator %>
            <%= f.label :elevator, "Thang máy" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :kitchen %>
            <%= f.label :kitchen, "Bếp" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :computer %>
            <%= f.label :computer %>
          </div>
        </div>
      </div>
      <div id ="room-maps" >
        <%= render "form_maps", f: f %>
      </div>
      <br/>
      <center>
        <%= f.submit "Tạo phòng", class: "btn btn-primary"%>
      </center>
    <% end %>
  </div>
</div>

app/views/rooms/_room.html.erb
<% @rooms.each do |room| %>
  <div class="col-md-4">
    <%= link_to room.name, room_path(room.id), method: :get %>
    <span>Giá: <%= room.price %> đồng</span>
    <p><%= room.province %></p>
    <ul class="imageSlide" >
      <% room.photos.each do |photo| %>
        <% if photo.image? %>
           <li><%= image_tag photo.image_url, size: "350x200" %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= provide(:title, "Sửa thông tin phòng") %>
<div id="room-new">
  <div class="row" >
    <%= form_for @room do |f| %>
      <div id = "room-infor" >
        <div class="col-md-6" >
          <div class="form-group" >
            <%= f.label :Tên_của_phòng %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group" >
            <%= f.label :Miêu_Tả %>
            <%= f.text_area :description, rows: 4 , class: "form-control"%>
          </div>
          <div class="form-group" >
            <%= f.label :home_type, "Loại nhà" %>
            <%= f.select :home_type, Room.home_types.keys,{},{ id: "home-type"} %>
          </div>
          <div class="form-group" >
            <%= f.label :price, "Gía phòng 1 đêm: " %>
            <%= f.number_field :price, step: "any" %><span> &nbsp;VND</span>
          </div>
          <div class="form-group" >
            <%= f.label :number_person, "Số người có thể ở:" %>
            <%= f.number_field :number_person, step: 1 %>
          </div>
          <div class="form-group inline" >
            <%= f.label :room_type, "Loại phòng" %>
            <%= f.select :room_type, Room.room_types.keys,{},{id: "room-type"}%>
          </div>
          <div class="form-group" >
            <%= f.label :province, "Tỉnh thành" %>
            <%= f.select :province, options_for_select(Room::PROVINCES),{},{id: "province"} %>
          </div>
          <div class="form-group" >
            <%= f.label :rule, "Quy định của phòng" %>
            <%= f.text_area :rule, rows: 3, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6" >
          <h2>Trang thiết bị của phòng</h2>
          <div class="form-group" >
            <%= f.check_box :internet %>
            <%= f.label :internet %>
          </div>
          <div class="form-group" >
            <%= f.check_box :tv %>
            <%= f.label :tv, "Ti vi" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :wifi %>
            <%= f.label :wifi, "Wi fi" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :kid %>
            <%= f.label :kid, "Trẻ em" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :aircondition %>
            <%= f.label :aircondition, "Điều hòa" %>
          </div>
          <div class="form-group"  >
            <%= f.check_box :elevator %>
            <%= f.label :elevator, "Thang máy" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :kitchen %>
            <%= f.label :kitchen, "Bếp" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :heating %>
            <%= f.label :heating, "Lò sửa" %>
          </div>
          <div class="form-group" >
            <%= f.check_box :computer %>
            <%= f.label :computer %>
          </div>
        </div>
      </div>
      <div id ="room-maps" >
        <%= render "form_maps", f: f %>
      </div>
      <br/>
      <center>
        <%= f.submit "Cập nhật", class: "btn btn-primary"%>
      </center>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row" >
  <%= form_tag(rooms_path, :method => "get", id: "search-form") do %>
    <div class="col-md-4" >
      <%= select_tag :search, options_for_select(Room::PROVINCES),{id: "search-room"} %>
    </div>
    <%= submit_tag "search", class: "btn btn-primary" %>
  <% end %>
</div>

<% if @rooms.present? %>
  <%= render "room" %>
<% else %>
  <p>There are no rooms containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/rooms/new.html.erb
<%= provide(:title, "thêm phòng") %>
<%= render "form_room" %>

app/views/rooms/show.html.erb
<div id="room-show">
  <div class="col-md-3" >
    <% if @room.user.avatar? %>
      <%= image_tag @room.user.avatar.url(:thumb), class: "img-circle" %>
    <% else %>
      <%= image_tag "user.png", class: "img-circle" %>
    <% end %>
    <br/>
    <div class="user-name" >
      <%= @room.user.name %><br/>
      <%= @room.user.email%>
    </div>
  </div>

  <div class="col-md-9" >
    <ul id="room-name">
      <ol><%= @room.name %></ol>
    </ul>
    <div class="col-md-3" >
      <p>Loại phòng: <%= @room.room_type %></p>
      <p>Loại nhà: <%= @room.home_type %></p>
      <p>Số khách: <%= @room.number_person %></p>
    </div>
    <div class="col-md-4" >
      <p style="font-weight: bold; font-size: 18px;" >Giá: <%= @room.price %>&nbsp;/Đêm</p>
    </div>
    <div class="col-md-3" >
      <%= link_to "Liên Lạc chủ phòng", new_conversation_path(:recipient => @room.user.id), class: "btn btn-primary" %>
      <div class="space"></div><br/>
      <% if !Favorite.room_exist(current_user.id, @room.id).present? && @room.user_id != current_user.id %>
        <%= form_for Favorite.new, remote: true do |f| %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit "Lưu vào danh sách yêu thích", class: "btn btn-primary" %>
        <% end %>
        <div id="saved">Đã Lưu</div>
      <% elsif @room.user_id == current_user.id %>
        <div>Đây là phòng của bạn</div>
      <% else %>
        <div>Đã Lưu</div>
      <% end %>
    </div>
  </div>
  <hr width="100%" size="5px"></hr>
  <div class="col-md-8" >
    <h4>Mô tả về phòng</h4>
    <p><%= @room.description %></p>
  </div>
  <hr width="100%" size="5px"></hr>
  <div class="col-md-12">
    <h4>Trang thiết bị</h4>
    <div class="col-md-6 thietbi" >
      <% if @room.internet? %>
        <p> <span class="glyphicon glyphicon-ok"></span>&nbsp;Internet </p>
      <% else %>
        <p><span class="glyphicon glyphicon-remove"></span>&nbsp;Internet</p>
      <% end %>
      <% if @room.tv? %>
        <p> <span class="glyphicon glyphicon-ok"></span>&nbsp;Tivi </p>
      <% else %>
        <p> <span class="glyphicon glyphicon-remove"></span>&nbsp;Tivi </p>
      <% end %>
      <% if @room.wifi? %>
        <p><span class="glyphicon glyphicon-ok"></span>&nbsp;Wifi</p>
      <% else %>
        <p><span class="glyphicon glyphicon-remove"></span>&nbsp;Wifi </p>
      <% end %>
      <% if @room.kid? %>
        <p><span class="glyphicon glyphicon-ok"></span>&nbsp;Trẻ em </p>
      <% else %>
        <p><span class="glyphicon glyphicon-remove"></span>&nbsp;Trẻ em</p>
      <% end %>
    </div>
    <div class="col-md-6 thietbi" >
      <% if @room.aircondition? %>
        <p><span class="glyphicon glyphicon-ok"></span>&nbsp;Điều hòa nhiệt độ</p>
      <% else %>
        <p><span class="glyphicon glyphicon-remove"></span>&nbsp;Điều hòa nhiệt độ</p>
      <% end %>
      <% if @room.elevator? %>
        <p><span class="glyphicon glyphicon-ok"></span>&nbsp;Thang máy</p>
      <% else %>
        <p><span class="glyphicon glyphicon-remove"></span>&nbsp;Thang máy</p>
      <% end %>
      <% if @room.kitchen? %>
        <p><span class="glyphicon glyphicon-ok"></span>&nbsp;Bếp</p>
      <% else %>
        <p><span class="glyphicon glyphicon-remove"></span>&nbsp;Bếp</p>
      <% end %>
      <% if @room.computer? %>
        <p><span class="glyphicon glyphicon-ok"></span>&nbsp;Máy tính</p>
      <% else %>
        <p><span class="glyphicon glyphicon-remove"></span>&nbsp;Máy tính</p>
      <% end %>
    </div>
  </div>
  <hr width="100%" size="5px" ></hr>
  <div class="col-md-12">
    <h4>Luật của phòng</h4>
    <p><%= @room.rule %></p>
  </div>
  <hr width="100%" size="5px" ></hr>
  <div class="col-md-12" >
    <p id="room-id"><%= @room.id %></p>
    <div class="col-md-6" >
      <div id="MapShow" style="width:550px;height:380px;" ></div>
    </div>
    <div class="col-md-6" >
      <ul class="imageSlide" >
        <% @room.photos.each do |photo| %>
          <% if photo.image? %>
            <li><%= image_tag photo.image_url, size: "800x400" %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to "Các bình luận", "#", id: "comment" %>
  <section id="comments-section">
    <ol id="comments">
      <%= render @comments %>
    </ol>
    <%= form_for [@room, @room.comments.new], remote: true do |f| %>
      <fieldset>
        <ol>
          <li>
            <%= f.hidden_field :room_id, value: @room.id %>
          </li>
          <li>
            <%= f.text_area :content, rows: 2, placeholder: "viết bình luận...", class: "form-control" %>
          </li>
          <br/>
          <li>
            <%= f.submit "Gửi bình luận", class: "btn btn-primary" %>
          </li>
        </ol>
      </fieldset>
    <% end %>
  </section>
</div>