config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root "rooms#index"

  resources :users do
    resources :rooms, only: :create
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :static_pages
  namespace :api do
    resources :comments
  end
  resources :rooms do
    resources :photos
    resources :comments
  end
  resources :photos
  resources :favorites
end

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="footer">
      <div class="container">
        <div class="clearfix">
          <div class="footer-logo"><a href="#">Bootflat</a></div>
          <dl class="footer-nav">
            <dt class="nav-title">PORTFOLIO</dt>
            <dd class="nav-item"><a href="#">Web Design</a></dd>
            <dd class="nav-item"><a href="#">Branding &amp; Identity</a></dd>
            <dd class="nav-item"><a href="#">Mobile Design</a></dd>
            <dd class="nav-item"><a href="#">Print</a></dd>
            <dd class="nav-item"><a href="#">User Interface</a></dd>
          </dl>
          <dl class="footer-nav">
            <dt class="nav-title">ABOUT</dt>
            <dd class="nav-item"><a href="#">The Company</a></dd>
            <dd class="nav-item"><a href="#">History</a></dd>
            <dd class="nav-item"><a href="#">Vision</a></dd>
          </dl>
          <dl class="footer-nav">
            <dt class="nav-title">GALLERY</dt>
            <dd class="nav-item"><a href="#">Flickr</a></dd>
            <dd class="nav-item"><a href="#">Picasa</a></dd>
            <dd class="nav-item"><a href="#">iStockPhoto</a></dd>
            <dd class="nav-item"><a href="#">PhotoDune</a></dd>
          </dl>
          <dl class="footer-nav">
            <dt class="nav-title">CONTACT</dt>
            <dd class="nav-item"><a href="#">Basic Info</a></dd>
            <dd class="nav-item"><a href="#">Map</a></dd>
            <dd class="nav-item"><a href="#">Conctact Form</a></dd>
          </dl>
        </div>
        <div class="footer-copyright text-center">Copyright &copy; 2014 Flathemes.All rights reserved.</div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="docs-header" >
  <nav class="navbar navbar-default navbar-custom" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "TickRoom", root_url, method: :get, class: "navbar-brand", id: "logo" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <% if current_user.role == "normal" %>
              <li><%= link_to "Tạo phòng",  new_room_path, method: :get %></li>
            <% end %>
            <li>
              <%= link_to mailbox_inbox_path do %>
                Hộp thư đến
                <span class="label label-danger pull-right"><%=unread_messages_count%></span>
                <em class="fa fa-inbox fa-lg"></em>
              <% end %>
            </li>
            <li class="round-image-50" >
              <%= if current_user.avatar?
                image_tag current_user.avatar.url(:thumb)
                else image_tag "user.png"
                end %>
            </li>
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle " data-toggle="dropdown">
                 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu" >
               <li><%= link_to "Trang cá nhân", user_path(current_user.id) %></li>
                <li><%= link_to "Cài đặt tài khoản", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Đăng suất", destroy_user_session_path, method: :delete  %></li>
              </ul>
            </li>
            <% else %>
            <li class="nav-link"><%= link_to "Đăng ký", new_user_registration_path %></li>
            <li class="nav-link"><%= link_to "Đăng nhập", new_user_session_path %></li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7v8FFLvG_ppubyMpkmr0VsNahiOY2q_k"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id = "body">
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>